workflows:
  SwipeToDeleteDemo-world:
    name: Swipe to delete demo workflow
    scripts:
      - name: Build project
        script: xcodebuild build -workspace "SwipeToDeleteDemo.xcworkspace" -scheme "SwipeToDeleteDemo" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: iOS test
        script: xcode-project run-tests \
          --workspace SwipeToDeleteDemo.xcworkspace \
          --scheme SwipeToDeleteDemo \
          --device "iPhone 11"
    publishing:
      email:
        recipients:
          - joshua@is-land.com.tw
